### ISSUE TITLE
Could a release for 1.7.9 be made please.

### ISSUE THREAD

**Issue by alext** [cloudfoundry/ruby-buildpack-release#2]
Please could we have a release for ruby-buildpack 1.7.9 - https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.7.9

thanks,
Alex

**Comment by sclevine** [comment]
A release for 1.7.9 has been created, but please note that this BOSH release is only intended to be used to supply buildpacks to new releases of cf-deployment. It may not contain every buildpack release, and it will be updated at a slower cadence than the buildpack releases due to additional testing necessary for integration with cf-deployment.
